### ISSUE TITLE
Big number error?

### ISSUE THREAD

**Issue by immartian** [Musicoin/client#1]
### Description

When I run "nw ." up, it display correctly of my wallet at the left corner, there's one music track in the main window, however without artwork. The rest problem is the music can't play even when I confirmed payment.  Instead, the log window displayed this message:

> /home/im/lab/musicoin/client/node_modules/bignumber.js/bignumber.js:1209
>             throw error;
>             ^
> 
> BigNumber Error: new BigNumber() not a base 16 number:

**Comment by immartian** [comment]
correction: the artwork appears after a while, though not immediately.

**Comment by immartian** [comment]
if @cwlau has further comment, please feel free as I see you have similar issue.

**Comment by cwlau** [comment]
The issue I encountered was an independent issue.  That was caused by npm module `bignumber.js` was missing.
